#baseURL = "https://example.com"
baseURL = "https://meowoo6.github.io/meowsblog/"
languageCode = "en-us"
title = "水绿条纹"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
publishDir = "docs"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博文"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "目录"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "MeoWoo"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = ""         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = ""
    Twitter = ""
    Email   = ""
    #Instagram = "xxoo"
    #Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    #Facebook = "xxoo"
    Telegram = ""
    #Dribbble = "xxoo"
    #Medium = "xxoo"

